### ISSUE TITLE
Code non functionning

### ISSUE THREAD

**Issue by montanier** [pelagios/pelagios-api-tutorial#1]
I tried to use the tutorial-map.js, but the request does not return any result. I suspect that the format to query the API is not correct.

I have write the following request to verify my doubts:

``` javascript
foo = function (query) { 
    jQuery.getJSON( 'http://pelagios.org/api-v3/search?query=' + query + '&verbose=true', function() {
        console.log( "success" );
    })
    .done(function() {
        console.log( "second success" );
    })
    .fail(function(jqxhr, textStatus, error) {
        var err = textStatus + ", " + error;
        console.log( "Request Failed: " + err );
    })
    .always(function() {
        console.log( "complete" );
    });
};
```

In the console log I get the following messages:

```
Request Failed: error, Not Found
complete
```

**Comment by rsimon** [comment]
Ouch - that's exactly what happens when we don't properly maintain our tutorial code ;-) Try now! (I should add: the API now returns geometry differently - shape collections rather than convex hulls, as shown in the screenshot - but you should see data now.)

Cheers,
R

**Comment by montanier** [comment]
Thank you for the fast answer. 

I think there is still a problem with the header of the answer. I now get the following errors in the console:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://pelagios.org/peripleo/search?query=herodotus&limit=100&verbose=true&type=item. (Reason: CORS header 'Access-Control-Allow-Origin' does not match '*, *').
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://pelagios.org/peripleo/search?query=homer&limit=100&verbose=true&type=item. (Reason: CORS header 'Access-Control-Allow-Origin' does not match '*, *').
```

If I got it right, I would say it can be corrected easily:
http://enable-cors.org/server.html

**Comment by rsimon** [comment]
Ah - sorry. CORS was, in fact, enabled twice (header set once by the Web proxy, and once by Peripleo itself). I disabled it on Peripleo now, so the header only exists once on the HTTP reply. Seemed to fix it. Let me know if not!

Cheers,
Rainer

**Comment by montanier** [comment]
Yes it works perfectly fine now. Thanks !

Jean-Marc
